# Programming Exercises Chapter 4
from graphics import *
import math

def moveCircle():
    win = GraphWin()
    shape = Circle(Point(50,50), 20)
    shape.setOutline("red")
    shape.setFill("red")
    shape.draw(win)
    for i in range(10):
        p = win.getMouse()
        c = shape.getCenter()
        dx = p.getX() - c.getX()
        dy = p.getY() - c.getY()
        shape.move(dx,dy)
    win.close()

def squares():
    win = GraphWin()
    shape = Rectangle(Point(1,1),Point(10,10))
    shape.setFill("red2")
    shape.setWidth(2)
    shape.draw(win)
    for i in range(10):
        p = win.getMouse()
        c = shape.getCenter()
        dx = p.getX() - c.getX()
        dy = p.getY() - c.getY()
        newShape = shape.clone()
        newShape.draw(win)
        newShape.move(dx, dy)
    message = Text(Point(100, 50), "Click again to quit").draw(win)
    win.getMouse()

def target():
    win = GraphWin("Target", 600, 600)
    white = Circle(Point(300,300), 250)
    white.setFill("white")
    white.draw(win)

    black = Circle(Point(300,300), 200)
    black.setFill("black")
    black.draw(win)
    
    blue = Circle(Point(300, 300), 150)
    blue.setFill("blue")
    blue.setOutline("blue")
    blue.draw(win)

    red = Circle(Point(300,300), 100)
    red.setFill("red")
    red.setOutline("red")
    red.draw(win)

    yellow = Circle(Point(300,300), 50)
    yellow.setFill("yellow")
    yellow.setOutline("yellow")
    yellow.draw(win)
    win.getMouse()


def face():
    win = GraphWin("Face", 800,800)
    win.setCoords(0.0, 0.0, 100.0, 100.0)
    head = Oval(Point(30.0,30.0), Point(70.0,90.0))
    head.setFill("beige")
    head.draw(win)
    eyeL = Oval(Point(35.0,70.0),Point(45.0,65.0))
    eyeL.setFill("white")
    eyeL.draw(win)
    eyeR = eyeL.clone()
    eyeR.move(20, 0)
    eyeR.draw(win)
    pupilL = Circle(Point(40,67.5), 2)
    pupilL.setFill("lightblue4")
    pupilL.draw(win)
    pupilL2 = Circle(Point(40,67.5), 0.4)
    pupilL2.setFill("black")
    pupilL2.draw(win)
    pupilR = pupilL.clone()
    pupilR.move(20, 0)
    pupilR.draw(win)
    pupilR2 = pupilL2.clone()
    pupilR2.move(20, 0)
    pupilR2.draw(win)
    nose1 = Line(Point(50,60), Point(55,50))
    nose1.setWidth(2)
    nose1.draw(win)
    nose2 = Line(Point(55,50), Point(50,50))
    nose2.setWidth(2)
    nose2.draw(win)
    mouth = Line(Point(44,42), Point(56, 42))
    mouth.setWidth(3)
    mouth.draw(win)
    win.getMouse()

def investmentChart3():
    # Create the graphics window
    win = GraphWin("Investment Growth Chart", 600, 500)
    win.setBackground("white")
    win.setCoords(-1.75, -200, 11.5, 10400)
    Text(Point(8,10000),"Initial investment:").draw(win)
    Text(Point(8,9000), "         Interest:").draw(win)
    inputMoney = Entry(Point(10, 10000), 5)
    inputMoney.setText("0.0")
    inputMoney.draw(win)
    inputInterest = Entry(Point(10, 9000), 5)
    inputInterest.setText("0.0")
    inputInterest.draw(win)
    Text(Point(-1,0), '0.0K').draw(win)
    Text(Point(-1,2500), '2.5K').draw(win)
    Text(Point(-1,5000), '5.0K').draw(win)
    Text(Point(-1,7500), '7.5K').draw(win)
    Text(Point(-1,10000), '10.0K').draw(win)

    win.getMouse()
    inputMoney = float(inputMoney.getText())
    inputInterest = float(inputInterest.getText())
    # Draw bar for initial investment
    bar = Rectangle(Point(0,0), Point(1, inputMoney))
    bar.setFill("green")
    bar.setWidth(2)
    bar.draw(win)
    # Draw bars for subsequent years
    for year in range(1,11):
        inputMoney = inputMoney * (1+inputInterest)
        bar = Rectangle(Point(year, 0), Point(year+1, inputMoney))
        bar.setFill("green")
        bar.setWidth(2)
        bar.draw(win)
    input("Press <Enter> to quit")
    win.close()

def circleIntersect():
    inputR = float(input("Enter the radius of the circle: "))
    inputY = float(input("Enter the y intercept: "))
    win = GraphWin("Circle Intersect", 600,600)
    win.setCoords(-10, -10, 10, 10)
    circle = Circle(Point(0,0), inputR)
    circle.draw(win)
    line = Line(Point(-10,inputY), Point(10, inputY))
    line.draw(win)
    iX = abs(math.sqrt(inputR**2 - inputY**2))
    intersect1 = Point(iX, inputY)
    intersect1.setFill("red")
    intersect1.setOutline("red")
    intersect1.draw(win)
    intersect2 = Point(-iX, inputY)
    intersect2.setFill("red")
    intersect2.setOutline("red")
    intersect2.draw(win)
    win.getMouse()

#moveCircle()
#squares()
#target()
#face()
#investmentChart3()
circleIntersect()
